import{useEffect,useMemo,useState}from'react';import{questions,grades}from'./data';import{mitsumuraTerms,type MiddleGrade}from'./mitsumura';import type{Question,Store,AnswerLog,StudyRecord}from'./types';import{load,save,localDate,mastery,memoryProfile,merge,fnv,migrate}from'./storage';import{coverage,examSpecs,readiness}from'./exam';import{courseQuestions,schoolCharacters}from'./curriculum';import{cumulativeKanji}from'./kanji-catalog';import{selectDaily,courseKey}from'./session';
type View='home'|'quiz'|'result'|'more'|'weekly'|'settings'|'transfer'|'plan'|'mock'|'history'|'worksheet'|'kanken'|'school'|'mastery'|'readiness';
const schoolGrades=['小学1年','小学2年','小学3年','小学4年','小学5年','小学6年','中学1年','中学2年','中学3年'];
const schoolToKanken:Record<string,string>={'小学1年':'10級','小学2年':'9級','小学3年':'8級','小学4年':'7級','小学5年':'6級','小学6年':'5級','中学1年':'4級','中学2年':'4級','中学3年':'3級'};
const gradeGuide:Record<string,string>={'10級':'小学1年修了程度・80字','9級':'小学2年修了程度・240字','8級':'小学3年修了程度・440字','7級':'小学4年修了程度・642字','6級':'小学5年修了程度・835字','5級':'小学6年修了程度・1,026字','4級':'中学校在学程度・1,339字','3級':'中学校卒業程度・1,623字'};
const enc=(o:unknown)=>btoa(unescape(encodeURIComponent(JSON.stringify(o)))).replaceAll('+','-').replaceAll('/','_').replaceAll('=','');
const dec=(s:string)=>JSON.parse(decodeURIComponent(escape(atob(s.replaceAll('-','+').replaceAll('_','/')+'==='.slice((s.length+3)%4)))));
const copy=async(text:string)=>{try{await navigator.clipboard.writeText(text);return true}catch{const t=document.createElement('textarea');t.value=text;t.style.position='fixed';t.style.opacity='0';document.body.append(t);t.select();const ok=document.execCommand('copy');t.remove();return ok}};
const pct=(a:number,b:number)=>b?Math.round(a/b*100):0;
function Button(p:React.ButtonHTMLAttributes<HTMLButtonElement>){return <button {...p} className={'btn '+(p.className||'')}/>}
function Notice({text}:{text:string}){return text?<div className={text.startsWith('×')||text.startsWith('⚠')?'notice bad':'notice'} role="status">{text}</div>:null}
export default function App(){
 const[store,setStore]=useState<Store>(load);const[view,setView]=useState<View>('home');const[index,setIndex]=useState(store.draft?.index||0);const[logs,setLogs]=useState<AnswerLog[]>(store.draft?.answers||[]);const[input,setInput]=useState(store.draft?.input||'');const[feedback,setFeedback]=useState(store.draft?.feedback||'');const[notice,setNotice]=useState('');const[started,setStarted]=useState(store.draft?.startedAt||new Date().toISOString());const[record,setRecord]=useState<StudyRecord|undefined>();
 const effectiveGrade=store.settings.courseMode==='school'?schoolToKanken[store.settings.schoolGrade]:store.settings.grade;
 const pool=useMemo(()=>courseQuestions(store.settings,questions),[store.settings]);
 const [sessionIds,setSessionIds]=useState<string[]>(store.draft?.questionIds||[]);
 const sessionList=sessionIds.map(id=>questions.find(q=>q.id===id)).filter((q):q is Question=>!!q);
 const daily=sessionList;


 useEffect(()=>{const u=new URL(location.href),data=u.searchParams.get('transfer'),sheet=u.searchParams.get('sheet');if(data){try{const pack=dec(data);if(!pack.data||pack.data.version!==1||!Array.isArray(pack.data.records)||fnv(JSON.stringify(pack.data))!==pack.checksum)throw 0;const merged=merge(load(),migrate(pack.data));save(merged);setStore(merged);setNotice('✓ 記録をうつしました。元の記録も残っています。');history.replaceState({},'',location.pathname)}catch{setNotice('× リンクがこわれています。いちばん新しいリンクを開いてね。')}}if(sheet){try{const parsed=dec(sheet);if(!Array.isArray(parsed)||!parsed.every(q=>q&&typeof q.question==='string'&&typeof q.answer==='string'))throw 0;setView('worksheet')}catch{setNotice('× プリントのリンクがこわれています。もう一度作ってね。')}}},[]);
 const persist=(s:Store)=>{if(courseKey(s.settings)!==courseKey(store.settings)){s={...s,draft:undefined};setSessionIds([]);setIndex(0);setLogs([]);setInput('');setFeedback('')}const where=save(s);setStore(s);if(where==='session')setNotice('⚠ 本体に記録できないため、一時保存しました。');if(where==='failed')setNotice('⚠ 記録できませんでした。結果はこの画面に残しています。')};
 const begin=(mock=false)=>{
 const draft=store.draft;
 if(!mock&&draft?.questionIds?.length&&draft.questionIds.every(id=>questions.some(q=>q.id===id))&&draft.courseKey===courseKey(store.settings)){
 setSessionIds(draft.questionIds);setIndex(draft.index);setLogs(draft.answers);setInput(draft.input||'');setFeedback(draft.feedback||'');setStarted(draft.startedAt);setView(draft.mode==='mini'?'mock':'quiz');return;
 }
 const list=mock?selectDaily(pool,store.records.flatMap(r=>r.answers)).concat(pool).filter((q,i,a)=>a.findIndex(x=>x.id===q.id)===i).slice(0,20):selectDaily(pool,store.records.flatMap(r=>r.answers));
 if(!list.length){setNotice('⚠ この範囲にはまだ問題がありません。コースを選び直してください。');return}
 const start=new Date().toISOString();setSessionIds(list.map(q=>q.id));setIndex(0);setLogs([]);setInput('');setFeedback('');setStarted(start);
 persist({...store,draft:{index:0,answers:[],startedAt:start,questionIds:list.map(q=>q.id),courseKey:courseKey(store.settings),mode:mock?'mini':'daily'}});
 history.pushState({view:mock?'mock':'quiz'},'',location.href);setView(mock?'mock':'quiz');scrollTo(0,0)};
 const answer=(q:Question)=>{if(feedback)return;const ok=!!(input.trim().normalize('NFKC')===q.answer.normalize('NFKC')||q.acceptedAnswers?.some(a=>input.trim().normalize('NFKC')===a.normalize('NFKC'))),message=ok?'○ 正解':'× もう一度';const l:AnswerLog={questionId:q.id,category:q.category,kanji:q.kanji,correct:ok,recall:q.choices.length===0,at:new Date().toISOString(),mode:view==='mock'?'mini':'daily'};const next=[...logs,l];setLogs(next);setFeedback(message);persist({...store,draft:{...store.draft,index,answers:next,startedAt:started,feedback:message,input,questionIds:sessionIds,courseKey:courseKey(store.settings),mode:view==='mock'?'mini':'daily'}})};
 const next=(isMock=false)=>{const list=sessionList;if(index+1<list.length){setIndex(index+1);setInput('');setFeedback('');persist({...store,draft:{...store.draft,index:index+1,answers:logs,startedAt:started,feedback:undefined,input:'',questionIds:sessionIds}});return}const all=[...store.records.flatMap(r=>r.answers),...logs],wrong=[...new Set(logs.filter(x=>!x.correct).flatMap(x=>x.kanji))],learned=[...new Set(logs.flatMap(x=>x.kanji))],mastered=learned.filter(k=>mastery(all,k)==='習得'),cats=[...new Set(logs.map(x=>x.category))],strengths=cats.filter(c=>pct(logs.filter(x=>x.category===c&&x.correct).length,logs.filter(x=>x.category===c).length)>=80),weaknesses=cats.filter(c=>pct(logs.filter(x=>x.category===c&&x.correct).length,logs.filter(x=>x.category===c).length)<80);const d=Math.max(1,Math.round((Date.now()-new Date(started).getTime())/60000));const r:StudyRecord={version:1,id:`${localDate()}-${isMock?'mini':'daily'}-${fnv(started)}`,date:localDate(),completedAt:new Date().toISOString(),durationMinutes:d,grade:store.settings.courseMode==='school'?`${store.settings.schoolGrade}・${store.settings.schoolTerm}学期`:`漢検${effectiveGrade}`,activity:isMock?'ミニ模試':'今日の学習',correct:logs.filter(x=>x.correct).length,total:logs.length,learnedKanji:learned,masteredKanji:mastered,wrongKanji:wrong,strengths,weaknesses,nextAction:wrong.length?`${wrong.join('・')}を復習`:'新しい漢字へ進む',steps:[true],answers:logs,mock:isMock?'mini':undefined};persist({...store,records:[...new Map([...store.records,r].map(x=>[x.id,x])).values()],draft:undefined});setRecord(r);setView('result');scrollTo(0,0)};
 const active=record||store.records.at(-1);const reportLink=()=>{const data=store,raw=JSON.stringify(data),pack=enc({data,checksum:fnv(raw)});if(pack.length>7000)return '記録が増えたため、引き継ぎ画面で記録ファイルを保存して移してください。';return `${location.origin}${location.pathname}?transfer=${pack}`};
 const streak=()=>{const ds=new Set(store.records.map(r=>r.date));let n=0,d=new Date();while(ds.has(localDate(d))){n++;d.setDate(d.getDate()-1)}return n};
 const dailyReport=(r:StudyRecord)=>`【今日の漢字学習】\n日付：${new Date(r.date+'T12:00').toLocaleDateString('ja-JP',{month:'long',day:'numeric'})}\n対象：${r.grade}\n進み具合：${r.total}問の練習を完了\n学習時間：${r.durationMinutes}分\n結果：${r.correct}/${r.total}問（${pct(r.correct,r.total)}%）\n\nできたこと：\n${r.strengths.map(x=>'・'+x).join('\n')||'・今日の学習を最後まで続けた'}\n\n復習すること：\n${r.wrongKanji.map(x=>'・「'+x+'」').join('\n')||'・なし'}\n\n次回：\n${r.nextAction}\n\n連続学習：${streak()}日\n引き継ぎ番号：${fnv(reportLink()).slice(-4).padStart(4,'0')}\n\n最新の記録引き継ぎリンク：\n${reportLink()}\n\n※このリンクには学習記録が含まれます。公開場所には貼らないでください。`;
 const doCopy=async(t:string)=>{const ok=await copy(t);setNotice(ok?'✓ コピーできました。送りたいアプリに貼り付けてね。':'× 自動コピーできませんでした。下の文章を長押ししてコピーしてください。')};
 const go=(v:View)=>{setNotice('');history.pushState({view:v},'',location.href);setView(v);scrollTo(0,0)};
 useEffect(()=>{const onPop=(e:PopStateEvent)=>setView((e.state?.view as View)||'home');addEventListener('popstate',onPop);return()=>removeEventListener('popstate',onPop)},[]);
 const backTo:View=['result','quiz','mock','school','kanken','mastery'].includes(view)?'home':view==='worksheet'&&active?'result':'more';
 const courseLabel=store.settings.courseMode==='school'?store.settings.schoolGrade:`漢検${store.settings.grade}`;
 return <main className={`view-${view}`}><header><button className="logo" onClick={()=>go('home')}>まいにち漢字</button><span className="course-chip">{courseLabel}</span></header>{view!=='home'&&<nav className="page-nav" aria-label="ページ移動"><button onClick={()=>go(backTo)}>← もどる</button><button onClick={()=>go('home')}>⌂ ホーム</button></nav>}<Notice text={notice}/>{view==='home'&&<Home store={store} progress={store.draft?store.draft.index:0} streak={streak()} begin={()=>begin()} more={()=>go('more')} go={go}/>} {view==='quiz'&&<Quiz q={daily[index]} index={index} total={daily.length} input={input} setInput={setInput} feedback={feedback} answer={answer} next={()=>next(false)} back={()=>go('home')}/>} {view==='mock'&&<Quiz q={sessionList[index]} index={index} total={sessionList.length} input={input} setInput={setInput} feedback={feedback} answer={answer} next={()=>next(true)} back={()=>go('home')}/>} {view==='result'&&active&&<Result r={active} streak={streak()} report={dailyReport(active)} copy={doCopy} go={go}/>} {view==='more'&&<More go={go} mock={()=>begin(true)}/>} {view==='mastery'&&<MasteryMap store={store}/>} {view==='readiness'&&<Readiness store={store}/>} {view==='kanken'&&<KankenPage store={store} update={persist} start={()=>begin()}/>} {view==='school'&&<SchoolPage store={store} update={persist} start={()=>begin()}/>} {view==='settings'&&<Settings store={store} update={persist} back={()=>go('more')}/>} {view==='history'&&<History records={store.records} back={()=>go('more')}/>} {view==='weekly'&&<Weekly store={store} link={reportLink()} copy={doCopy} back={()=>go('more')}/>} {view==='transfer'&&<Transfer store={store} update={persist} link={reportLink()} copy={doCopy} back={()=>go('more')}/>} {view==='plan'&&<Plan store={store} copy={doCopy} back={()=>go('more')}/>} {view==='worksheet'&&<Worksheet r={active} copy={doCopy} back={()=>go(active?'result':'home')}/>}<footer><span>記録はこの端末に保存されます</span></footer>{view!=='quiz'&&view!=='mock'&&<nav className="bottom-nav" aria-label="メインメニュー">{([{v:'home',icon:'⌂',label:'ホーム'},{v:'mastery',icon:'字',label:'習得マップ'},{v:'more',icon:'•••',label:'メニュー'}]as const).map(x=><button key={x.v} aria-current={view===x.v?'page':undefined} onClick={()=>go(x.v)}><span aria-hidden="true">{x.icon}</span>{x.label}</button>)}</nav>}</main>
}
function Home({store,streak,begin,more,go}:{store:Store;progress:number;streak:number;begin:()=>void;more:()=>void;go:(v:View)=>void}){
 const school=store.settings.courseMode==='school',course=school?store.settings.schoolGrade:`漢検${store.settings.grade}`,count=courseQuestions(store.settings,questions).length,resume=store.draft?.courseKey===courseKey(store.settings),today=store.records.filter(r=>r.date===localDate()&&!r.mock),completed=today.length>0;
 const answered=resume?store.draft!.answers.length:0,target=resume?store.draft!.questionIds?.length||5:5,mini=resume&&store.draft!.mode==='mini';
 return <section className="home"><p className="eyebrow">毎日すこしずつ、覚えよう</p><h1>{resume?'つづきから、もう一歩。':completed?'今日も、よくがんばったね。':'今日の5問から、はじめよう。'}</h1><p className="home-intro">読みと書きで、漢字を自分の力に。</p><section className="study-card" aria-label="今日の学習"><div className="current-course"><div><span>いまのコース</span><b>{course}{school&&course.startsWith('中学')&&<small>・{store.settings.schoolTerm}学期</small>}</b></div><button onClick={()=>go(school?'school':'kanken')}>変更</button></div><div className="study-meta"><span>{mini?'ミニ模試':'読み・書き'} / {target}問</span><span>{mini?'自分のペースで':'約5〜10分'}</span></div>{count?<><Button className="primary hero" onClick={begin}>{resume?'つづきから':'きょうの5問をはじめる'}<span aria-hidden="true"> →</span></Button><p className="study-hint">{resume?`${answered}問回答済み。前の問題から再開できます。`:completed?'もう少し練習したいときは、次の5問へ。':'復習と新しい漢字を、あなたに合わせて選びます。'}</p></>:<div className="blocked"><b>このコースは準備中です</b><p>別の級の問題は出しません。</p><Button onClick={()=>go('kanken')}>コースを選ぶ</Button></div>}</section><div className="summary"><div><b>{completed?'✓ 完了':resume?`${answered}/${target}問`:'これから'}</b><small>今日の学習</small></div><div><b>{streak}日</b><small>連続学習</small></div></div><h2 className="section-title">できるようになったこと</h2><div className="home-links"><Button className="map-shortcut" onClick={()=>go('mastery')}>できる漢字を見る　›</Button><Button onClick={()=>go('history')}>これまでの記録　›</Button></div><details className="course-disclosure"><summary>学ぶコースをえらぶ</summary><div className="course-links"><Button onClick={()=>go('kanken')}>漢検の級からえらぶ</Button><Button onClick={()=>go('school')}>学校の学年からえらぶ</Button></div></details><Button className="quiet" onClick={more}>そのほか・おうちの人用</Button></section>;
}

function Quiz({q,index,total,input,setInput,feedback,answer,next,back}:{q:Question;index:number;total:number;input:string;setInput:(s:string)=>void;feedback:string;answer:(q:Question)=>void;next:()=>void;back:()=>void}){
 if(!q)return <section><h1>問題がありません</h1><Button onClick={back}>もどる</Button></section>;
 return <section className="quiz"><div className="quiz-meta"><span className="question-kind">{q.category}</span><span>{index+1} / {total}問</span></div><div className="progress" role="progressbar" aria-label="回答済みの問題" aria-valuemin={0} aria-valuemax={total} aria-valuenow={index+(feedback?1:0)}><i style={{width:`${(index+(feedback?1:0))/total*100}%`}}/></div><div className="question-card"><h1>{q.question}</h1>{q.choices.length?<div className="choices">{q.choices.map(c=><Button key={c} aria-pressed={input===c} className={input===c?'selected':''} disabled={!!feedback} onClick={()=>setInput(c)}>{c}</Button>)}</div>:<><label className="answer-label" htmlFor="answer-input">答え</label><input id="answer-input" key={q.id} aria-describedby="answer-help" disabled={!!feedback} value={input} onChange={e=>setInput(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'&&!e.nativeEvent.isComposing&&e.keyCode!==229&&input.trim()&&!feedback){e.preventDefault();answer(q)}}} autoFocus inputMode="text" enterKeyHint="done" autoComplete="off" spellCheck={false}/><p id="answer-help" className="source-note">{q.category==='読み'?'ひらがなで入力してね。':'漢字に変換して入力してね。'}</p></>}</div>{feedback&&<div role="status" className={'feedback '+(feedback[0]==='○'?'ok':'ng')}><b>{feedback[0]==='○'?'○ 正解':'次に覚えよう'}</b>{feedback[0]==='×'&&<p className="correct-answer">正解：{q.answer}</p>}<p>{q.explanation}</p></div>}<div className="quiz-actions">{!feedback?<Button className="primary" disabled={!input.trim()} onClick={()=>answer(q)}>こたえを決める</Button>:<Button className="primary" onClick={next}>{index+1===total?'きょうの結果を見る':'つぎの問題'}</Button>}</div><button className="back" onClick={back}>中断してホームへ（つづきは保存されます）</button></section>;
}

function Result({r,streak,report,copy,go}:{r:StudyRecord;streak:number;report:string;copy:(s:string)=>void;go:(v:View)=>void}){return <section className="result"><p className="eyebrow">✓ きょうの問題 完了</p><h1>おつかれさま！</h1><p>{r.total}問の練習をやりきりました。</p><div className="score"><div><small>正解した問題</small><b>{r.correct}<span> / {r.total}問</span></b></div><span>{pct(r.correct,r.total)}%</span></div><div className="cards"><article><h2>練習した漢字</h2><p className="learned-characters">{r.learnedKanji.join('　')||'—'}</p></article><article><h2>{r.wrongKanji.length?'次に復習する漢字':'全部正解！'}</h2><p>{r.wrongKanji.join('・')||'時間を空けて、また思い出してみよう。'}</p></article></div><p className="result-streak">連続学習 {streak}日 · 今日の練習 {r.durationMinutes}分</p><Button className="primary" onClick={()=>go('home')}>ホームへ</Button>{r.wrongKanji.length>0&&<Button onClick={()=>go('worksheet')}>間違えた漢字をプリントで復習</Button>}<details className="report-details"><summary>おうちの人に結果を伝える</summary><Button onClick={()=>copy(report)}>おうちの人に報告をコピー</Button><textarea className="manual" readOnly value={report} aria-label="報告文"/></details><Button className="quiet" onClick={()=>go('mastery')}>できる漢字を見る</Button></section>}

function More({go,mock}:{go:(v:View)=>void;mock:()=>void}){return <section><p className="eyebrow">必要なときだけ使うメニュー</p><h1>そのほか</h1><h2 className="section-title">学ぶコース</h2><div className="menu"><Button onClick={()=>go('kanken')}>漢検級別ページ</Button><Button onClick={()=>go('school')}>学年別ページ</Button></div><h2 className="section-title">力をためす・記録を見る</h2><div className="menu"><Button onClick={()=>go('readiness')}>合格までの道のり</Button><Button onClick={()=>go('mastery')}>漢字習得マップ</Button><Button onClick={mock}>週1回のミニ模試</Button><Button onClick={()=>go('history')}>これまでの記録</Button></div><h2 className="section-title">おうちの人用</h2><div className="menu"><Button onClick={()=>go('weekly')}>週間報告</Button><Button onClick={()=>go('plan')}>今後7日分の学習計画</Button><Button onClick={()=>go('transfer')}>別のスマホでつづける</Button><Button onClick={()=>go('settings')}>試験日と時間の設定</Button></div></section>}
function KankenPage({store,update,start}:{store:Store;update:(s:Store)=>void;start:()=>void}){const choose=(grade:string)=>update({...store,settings:{...store.settings,grade,courseMode:'kanken'}}),current=coverage(store.settings.grade,questions);return <section><p className="eyebrow">目標の級で学ぶ</p><h1>漢検の級で学ぶ</h1><p>その級までに習う漢字を累積で出題します。読み書きの基礎練習を追加しました。漢検の全分野・本番形式の模試はまだ未完成です。</p>{store.settings.courseMode==='kanken'&&<p className="selection-summary">選択中：漢検{store.settings.grade}</p>}{store.settings.courseMode==='kanken'&&current.questions>0?<Button className="primary" onClick={start}>この級で今日の学習をはじめる</Button>:store.settings.courseMode==='kanken'?<div className="blocked"><b>⚠ この級はまだ始められません</b><p>別の級の問題で代用せず、正しい教材がそろうまで止めています。</p></div>:null}<h2 className="section-title">目標の級を選ぶ</h2><div className="level-grid">{grades.map(g=>{const c=coverage(g,questions);return <button key={g} aria-pressed={store.settings.courseMode==='kanken'&&store.settings.grade===g} className={store.settings.courseMode==='kanken'&&store.settings.grade===g?'level active':'level'} onClick={()=>choose(g)}><b>漢検{g}</b><span>{gradeGuide[g]}</span><small>{c.questions?`教材 ${c.questions}問・${c.categories}/${c.totalCategories}分野`:'⚠ 教材準備中'}</small><em>{store.settings.courseMode==='kanken'&&store.settings.grade===g?'✓ えらんでいます':'この級にする'}</em></button>})}</div><p className="source-note">教材が漢検の全対象漢字・全分野を満たすまでは、「合格までの道のり」で未完成と表示します。</p></section>}
function SchoolPage({store,update,start}:{store:Store;update:(s:Store)=>void;start:()=>void}){const choose=(schoolGrade:string)=>update({...store,settings:{...store.settings,schoolGrade,grade:schoolToKanken[schoolGrade],courseMode:'school'}}),middle=store.settings.courseMode==='school'&&store.settings.schoolGrade.startsWith('中学')?store.settings.schoolGrade as MiddleGrade:null,term=store.settings.schoolTerm;return <section><p className="eyebrow">教科書の範囲で学ぶ</p><h1>学校の学年で学ぶ</h1><p>学年と学期を選んで、学校の漢字を練習しよう。</p>{middle&&<section className="term-panel"><p className="eyebrow">光村図書 令和7年度版</p><h2>定期テストの学期を選ぶ</h2><div className="term-tabs">{([1,2,3]as const).map(t=><button aria-pressed={term===t} className={term===t?'active':''} onClick={()=>update({...store,settings:{...store.settings,schoolTerm:t}})} key={t}>{t}学期</button>)}</div><details className="unit-details"><summary>{middle}・{term}学期の教科書範囲を見る</summary><ul>{mitsumuraTerms[middle][term].map(u=><li key={u}>{u}</li>)}</ul></details><p className="source-note">学校の進度で前後する場合は、テスト範囲表を優先してください。教科書の単元別漢字一覧に基づき、この学期の基本読み書きを出題します。すべての語句・音訓や定期テスト形式を網羅するものではありません。</p></section>}{store.settings.courseMode==='school'&&<><p>{courseQuestions(store.settings,questions).length}問・{schoolCharacters(store.settings.schoolGrade,middle?term:undefined).length}字を収録</p><Button className="primary" disabled={!courseQuestions(store.settings,questions).length} onClick={start}>{middle?'この学期の漢字をはじめる':'この学年で今日の学習をはじめる'}</Button></>}<h2 className="section-title">学年を変更する</h2><div className="school-groups"><h2>小学生</h2><div className="level-grid compact">{schoolGrades.slice(0,6).map(g=><button key={g} aria-pressed={store.settings.courseMode==='school'&&store.settings.schoolGrade===g} className={store.settings.courseMode==='school'&&store.settings.schoolGrade===g?'level active':'level'} onClick={()=>choose(g)}><b>{g}</b><span>漢検{schoolToKanken[g]}めやす</span><em>{store.settings.courseMode==='school'&&store.settings.schoolGrade===g?'✓ えらんでいます':'この学年にする'}</em></button>)}</div><h2>中学生</h2><div className="level-grid compact">{schoolGrades.slice(6).map(g=><button key={g} aria-pressed={store.settings.courseMode==='school'&&store.settings.schoolGrade===g} className={store.settings.courseMode==='school'&&store.settings.schoolGrade===g?'level active':'level'} onClick={()=>choose(g)}><b>{g}</b><span>光村図書・漢検{schoolToKanken[g]}（目安）</span><em>{store.settings.courseMode==='school'&&store.settings.schoolGrade===g?'✓ えらんでいます':'この学年にする'}</em></button>)}</div></div></section>}
function Settings({store,update,back}:{store:Store;update:(s:Store)=>void;back:()=>void}){const [s,setSettings]=useState(store.settings);return <section><p className="eyebrow">おうちの人用</p><h1>試験日と学習時間</h1><p className="source-note">学ぶコースは、ホームの「変更」から選べます。</p><form onSubmit={e=>{e.preventDefault();update({...store,settings:s});back()}}><label>漢検の目標<select value={s.grade} onChange={e=>setSettings({...s,grade:e.target.value})}>{grades.map(g=><option key={g} value={g}>漢検{g}</option>)}</select></label><label>試験日<input type="date" value={s.examDate} onChange={e=>setSettings({...s,examDate:e.target.value})}/></label><label>1日で学ぶ時間（分）<input type="number" required min="10" max="90" value={s.dailyLimitMinutes} onChange={e=>setSettings({...s,dailyLimitMinutes:+e.target.value})}/></label><Button type="submit" className="primary">✓ 保存してもどる</Button></form></section>}

function Readiness({store}:{store:Store}){const grade=store.settings.courseMode==='school'?schoolToKanken[store.settings.schoolGrade]:store.settings.grade,r=readiness(grade,questions,store.records),spec=examSpecs[grade];return <section className="readiness"><p className="eyebrow">漢検{grade}</p><h1>合格までの道のり</h1><div className={r.passed?'readiness-result ready':'readiness-result'}><b>{r.passed?'✓ 合格点に届く力が安定しています':'まだ合格判定はできません'}</b><p>{r.reason}</p></div><h2>判定に使う3つの確認</h2><div className="check-list"><article><b>{r.bankReady?'✓':'△'} 出題範囲</b><p>{r.characters}/{r.targetCharacters}字・{r.categories}/{r.totalCategories}分野・{r.questions}問</p>{r.missing.length>0&&<small>未収録：{r.missing.join('・')}</small>}</article><article><b>{r.evidenceReady?'✓':'△'} 模試と学習記録</b><p>{r.mockRate===null?'模試がまだありません':`直近の模試平均 ${r.mockRate}%`}</p><small>本番形式の模試2回と、各分野3問以上で判定。現在のミニ模試は合格判定に使いません。</small></article><article><b>{r.passed?'✓':'△'} 合格基準</b><p>漢検{grade}は{spec.pass}%程度が目安</p><small>一度だけでなく、分野別に安定した正解を確認</small></article></div><h2>分野ごとの確認</h2><div className="category-list">{r.byCategory.map(x=><div key={x.category}><span>{x.category}</span><b>{x.rate===null?'未確認':`${x.rate}%`}</b><small>{x.total}問</small></div>)}</div><p className="source-note">出題分野・合格基準は日本漢字能力検定協会の級別基準に合わせています。教材数が足りない間は、点数が高くても合格圏と表示しません。</p></section>}
function MasteryMap({store}:{store:Store}){const[mode,setMode]=useState<'school'|'kanken'>(store.settings.courseMode),[group,setGroup]=useState(store.settings.courseMode==='school'?store.settings.schoolGrade:store.settings.grade),[filter,setFilter]=useState('すべて');const logs=store.records.flatMap(r=>r.answers),groups=mode==='school'?schoolGrades:grades;useEffect(()=>{setGroup(mode==='school'?store.settings.schoolGrade:store.settings.grade)},[mode]);const chars=[...(mode==='kanken'?cumulativeKanji(group):schoolCharacters(group))],rows=chars.map(kanji=>({kanji,...memoryProfile(logs,kanji)})),shown=filter==='すべて'?rows:filter==='復習日'?rows.filter(r=>r.due&&r.status!=='未学習'):rows.filter(r=>r.status===filter),counts=Object.fromEntries(['未学習','練習中','もう少し','習得'].map(s=>[s,rows.filter(r=>r.status===s).length])),done=counts['習得']||0;return <section className="mastery-map"><p className="eyebrow">できるようになったこと</p><h1>漢字習得マップ</h1><p>漢検はその級までの全対象字、学年は教科書の一覧を表示します。時間を空けて読み書きに正解すると、習得に近づきます。</p><div className="map-mode" role="tablist" aria-label="習得マップの分け方"><button role="tab" aria-selected={mode==='school'} className={mode==='school'?'active':''} onClick={()=>setMode('school')}>学年ごと</button><button role="tab" aria-selected={mode==='kanken'} className={mode==='kanken'?'active':''} onClick={()=>setMode('kanken')}>漢検レベルごと</button></div><label className="map-select">見る範囲<select value={group} onChange={e=>setGroup(e.target.value)}>{groups.map(g=><option key={g} value={g}>{mode==='kanken'?`漢検${g}`:g}</option>)}</select></label><div className="map-progress" aria-label={`${rows.length}字中${done}字習得`}><div><b>{done}/{rows.length}字</b><span>習得</span></div><i><span style={{width:`${pct(done,rows.length)}%`}}/></i></div><div className="status-filters">{['すべて','復習日','未学習','練習中','もう少し','習得'].map(s=><button aria-pressed={filter===s} className={filter===s?'active':''} onClick={()=>setFilter(s)} key={s}>{s==='復習日'?'⏰ 復習':s==='未学習'?'未学習':s==='練習中'?'練習中':s==='もう少し'?'もう少し':s==='習得'?'習得':'全部'} {s!=='すべて'&&s!=='復習日'&&counts[s]}</button>)}</div>{shown.length?<div className="kanji-grid">{shown.map(({kanji,status,due,nextReview})=><article className={`kanji-tile status-${status}`} key={kanji}><b>{kanji}</b><span>{status==='未学習'?'○ 未学習':status==='練習中'?'△ 練習中':status==='もう少し'?'↑ もう少し':'✓ 習得'}</span>{status!=='未学習'&&<small>{due?'今日復習':`次 ${nextReview?.slice(5).replace('-','/')}`}</small>}</article>)}</div>:<div className="empty-map"><b>{filter==='復習日'?'今日の復習はありません':'この条件に合う漢字はありません'}</b><p>{filter==='復習日'?'次の復習日まで待つと、記憶の確認になります。':'ほかの状態を選ぶと漢字が表示されます。'}</p></div>}<aside className="mastery-rule"><h2>長く覚えたと判定する条件</h2><ul><li>1・3・7・14・30日を目安に思い出す</li><li>5日以上に分け、30日以上かけて正解</li><li>読みと書きの両方で正解</li><li>間違えたら今日から復習し直す</li></ul></aside></section>}
function History({records,back}:{records:StudyRecord[];back:()=>void}){return <section><h1>これまでの記録</h1>{records.length?records.slice().reverse().map(r=><article className="history" key={r.id}><b>{r.date}　{r.activity}</b><span>{r.correct}/{r.total}問（{pct(r.correct,r.total)}%）</span><small>次：{r.nextAction}</small></article>):<p>まだ記録はありません。</p>}<Button onClick={back}>← もどる</Button></section>}
function weeklyText(s:Store,link:string){const now=Date.now(),recent=s.records.filter(r=>now-new Date(r.completedAt).getTime()<7*864e5),prev=s.records.filter(r=>{const d=now-new Date(r.completedAt).getTime();return d>=7*864e5&&d<14*864e5}),total=recent.reduce((a,r)=>a+r.total,0),correct=recent.reduce((a,r)=>a+r.correct,0),mins=recent.reduce((a,r)=>a+r.durationMinutes,0),learn=[...new Set(recent.flatMap(r=>r.learnedKanji))],master=[...new Set(recent.flatMap(r=>r.masteredKanji))],wrong=[...new Set(recent.flatMap(r=>r.wrongKanji))],mock=recent.filter(r=>r.mock).at(-1),days=s.settings.examDate?Math.ceil((new Date(s.settings.examDate+'T12:00').getTime()-now)/864e5):null,ready=readiness(s.settings.grade,questions,s.records),judgement=ready.passed?'合格点に届く力が安定':ready.reason;return `【漢検${s.settings.grade} 週間報告】\n学習：${new Set(recent.map(r=>r.date)).size}/7日\n合計：${mins}分・${total}問\n平均正答率：${pct(correct,total)}%\n新しく学習：${learn.length}字\n習得：${master.length}字\n復習中：${wrong.length}字\n\nよくできたこと：\n${[...new Set(recent.flatMap(r=>r.strengths))].map(x=>'・'+x).join('\n')||'・学習を続けた'}\n\n来週の重点：\n${[...new Set(recent.flatMap(r=>r.weaknesses))].map(x=>'・'+x).join('\n')||'・新しい漢字'}\n\nミニ模試：${mock?`${mock.correct}/${mock.total}問`:'未実施'}\n判定：${judgement}\n前週との比較：${recent.length-prev.length>=0?'+':''}${recent.length-prev.length}回\n試験まで：${days===null?'試験日を設定してください':Math.max(0,days)+'日'}\n\n最新の端末引き継ぎリンク：\n${link}\n※このリンクには学習記録が含まれます。公開場所には貼らないでください。`}
function Weekly({store,link,copy,back}:{store:Store;link:string;copy:(s:string)=>void;back:()=>void}){const t=weeklyText(store,link);return <section><h1>7日間のまとめ</h1><pre>{t}</pre><Button className="primary" onClick={()=>copy(t)}>週間報告をコピー</Button><textarea className="manual" readOnly value={t} aria-label="週間報告文"/><Button onClick={back}>← もどる</Button></section>}
function Transfer({store,update,link,copy,back}:{store:Store;update:(s:Store)=>void;link:string;copy:(s:string)=>void;back:()=>void}){const [message,setMessage]=useState('');const backup=()=>{const blob=new Blob([JSON.stringify(store)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`kanji-records-${localDate()}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)};const restore=async(file?:File)=>{if(!file)return;try{if(file.size>20*1024*1024)throw 0;const data=JSON.parse(await file.text());if(data.version!==1||!Array.isArray(data.records))throw 0;update(merge(store,migrate(data)));setMessage('✓ 記録を読み込みました。')}catch{setMessage('× 記録ファイルを確認してください。')}};return <section><h1>別のスマホでつづける</h1><Notice text={message}/><h2>記録ファイルでうつす</h2><p>長く学習した記録も、ファイルならまとめてうつせます。保存したファイルを新しい端末で開いてください。</p><Button onClick={backup}>記録ファイルを保存</Button><label>記録ファイルを読み込む<input type="file" accept=".json,application/json" onChange={e=>restore(e.target.files?.[0])}/></label><h2>短い記録はリンクでもうつせます</h2><p className="warning">⚠ このリンクには学習記録が含まれます。公開場所には貼らないでください。</p><div className="pin">引き継ぎ番号 <b>{fnv(link).slice(-4).padStart(4,'0')}</b></div><Button className="primary" onClick={()=>copy(link)}>最新リンクをコピー</Button><textarea readOnly value={link} aria-label="引き継ぎリンク"/><h2>記録をうつす方法</h2><ol><li>このリンクをGoogle Chatに貼る</li><li>新しい端末で、いちばん新しいリンクを開く</li><li>元と新しい記録が一つにまとまる</li></ol><Button onClick={back}>← もどる</Button></section>}
function planData(s:Store){const tasks:Record<string,unknown>[]=[],base=new Date(),titles:Record<string,string>={daily:'今日の5問',mock:'ミニ模試',mock_review:'模試の復習',wrong_kanji_review:'間違えた漢字の復習',new_kanji:'新しい漢字',reading:'読み問題',writing:'書き問題',worksheet:'類題プリント'};for(let n=1;n<=7;n++){const d=new Date(base);d.setDate(d.getDate()+n);const date=localDate(d),mock=d.getDay()===0,types=mock?['mock','mock_review']:['daily'];const each=Math.max(3,Math.floor(s.settings.dailyLimitMinutes/types.length));for(const type of types)tasks.push({id:`kanji-${date}-${type}`,source:'kanken-app',date,type,title:titles[type],description:type==='wrong_kanji_review'?'前回間違えた漢字を復習する':'今日の課題を進める',estimatedMinutes:each,priority:'required',status:'pending',launchUrl:`${location.origin}${location.pathname}`,tags:['漢字','漢検',type]})}return{schema:'kanji-study-plan',version:1,generatedAt:new Date().toISOString(),exam:{name:`漢検${s.settings.grade}`,date:s.settings.examDate,goal:'合格'},learner:{dailyLimitMinutes:s.settings.dailyLimitMinutes},tasks}}
function Plan({store,copy,back}:{store:Store;copy:(s:string)=>void;back:()=>void}){const plan=planData(store),t=JSON.stringify(plan,null,2),dates=[...new Set(plan.tasks.map(x=>String(x.date)))];return <section><p className="eyebrow">おうちの人用</p><h1>今後7日分の学習計画</h1><p>毎日の5問を基本に、日曜日はミニ模試で力をためします。</p><div className="cards">{dates.map(date=><article key={date}><h2>{new Date(date+'T12:00').toLocaleDateString('ja-JP',{month:'long',day:'numeric',weekday:'short'})}</h2><p>{plan.tasks.filter(x=>x.date===date).map(x=>String(x.title)).join('・')}</p></article>)}</div><details><summary>ほかのアプリ用のデータを開く</summary><p className="source-note">学習計画を取り込めるアプリに貼り付けるためのデータです。</p><Button onClick={()=>copy(t)}>今後7日分の漢検タスクをコピー</Button><textarea className="json" readOnly value={t} aria-label="学習計画データ"/></details><Button className="quiet" onClick={back}>← もどる</Button></section>}

function Worksheet({r,copy,back}:{r?:StudyRecord;copy:(s:string)=>void;back:()=>void}){let linked:Question[]=[];try{const p=new URL(location.href).searchParams.get('sheet');if(p){const parsed=dec(p);if(Array.isArray(parsed)&&parsed.every(q=>q&&typeof q.question==='string'&&typeof q.answer==='string'))linked=parsed}}catch{/* error notice is shown by App */}const made=(r?.answers.filter(a=>!a.correct).map(a=>questions.find(q=>q.id===a.questionId)).filter(Boolean) as Question[]||[]).map(q=>q.similar?({...q,...q.similar}):({...q,question:`もう一度思い出そう：${q.question}`}));const qs=linked.length?linked:made;const payload=enc(qs);const link=`${location.origin}${location.pathname}?sheet=${payload}`;const pdf=()=>window.print();return <section className="sheet"><div className="print-problems"><h1>類題プリント・問題</h1><p>{r?.date||localDate()}　{r?.grade||''}</p>{qs.length?qs.map((q,i)=><article key={q.id||i}><h2>{i+1}. {q.question}</h2><div className="squares">□ □ □ □ □ □</div><details><summary>答えと解説を見る</summary><b>{q.answer}</b><p>{q.explanation}</p></details></article>):<p>今日は間違いがありません。プリントは必要ありません。</p>}</div>{qs.length>0&&<section className="print-answers" aria-label="類題プリントの答え"><h1>類題プリント・答え</h1><p>{r?.date||localDate()}　{r?.grade||''}</p>{qs.map((q,i)=><article key={`answer-${q.id||i}`}><h2>{i+1}. {q.answer}</h2><p>{q.explanation}</p></article>)}</section>}<p className="pdf-help">「PDFを保存」を押した後、Androidの印刷画面で「PDF形式で保存」を選んでください。日本語のまま保存されます。</p><Button className="primary" disabled={!qs.length} onClick={pdf}>PDFを保存</Button><Button disabled={!qs.length} onClick={()=>copy(link)}>印刷リンクをコピー</Button><Button className="quiet" onClick={back}>← もどる</Button></section>}
