import type {Store,StudyRecord,AnswerLog} from './types';
export const KEY='kanji-study-v1';
export const localDate=(d=new Date())=>{const y=d.getFullYear(),m=String(d.getMonth()+1).padStart(2,'0'),day=String(d.getDate()).padStart(2,'0');return `${y}-${m}-${day}`};
export const emptyStore=():Store=>({version:1,settings:{grade:'6級',examDate:'',dailyLimitMinutes:45,courseMode:'kanken',schoolGrade:'小学5年',schoolTerm:1},records:[],importedIds:[]});
export function migrate(raw:unknown):Store{try{const x=typeof raw==='string'?JSON.parse(raw):raw as any;if(!x||typeof x!=='object')return emptyStore();const base=emptyStore();const records=Array.isArray(x.records)?x.records.filter((r:any)=>r&&r.id&&Number.isFinite(r.total)).map((r:any)=>({...r,version:1,steps:r.steps??[true,true,true,true,true],answers:r.answers??[]})):[];return {...base,...x,version:1,settings:{...base.settings,...x.settings},records:[...new Map(records.map((r:StudyRecord)=>[r.id,r])).values()]}}catch{return emptyStore()}}
export function load():Store{return migrate(localStorage.getItem(KEY)||sessionStorage.getItem(KEY))}
export function save(s:Store){try{localStorage.setItem(KEY,JSON.stringify(s));return 'local'}catch{try{sessionStorage.setItem(KEY,JSON.stringify(s));return 'session'}catch{return 'failed'}}}
const DAY=864e5,INTERVALS=[1,3,7,14,30];
export function memoryProfile(logs:AnswerLog[],kanji:string,now=Date.now()){const a=logs.filter(x=>x.kanji.includes(kanji)).sort((x,y)=>new Date(x.at).getTime()-new Date(y.at).getTime());if(!a.length)return{status:'未学習',due:true,nextReview:null,successfulDays:0,spanDays:0};const correct=a.filter(x=>x.correct),dates=[...new Set(correct.map(x=>x.at.slice(0,10)))],first=correct[0]&&new Date(correct[0].at).getTime(),last=correct.at(-1)&&new Date(correct.at(-1)!.at).getTime(),span=first&&last?Math.floor((last-first)/DAY):0,latest=a.at(-1)!,latestWrong=!latest.correct,read=correct.some(x=>x.category==='読み'),write=correct.some(x=>x.category==='書き'),level=Math.min(dates.length,INTERVALS.length),gap=INTERVALS[Math.max(0,level-1)],dueAt=latestWrong?now:(last||now)+gap*DAY,due=now>=dueAt;let status='練習中';if(dates.length>=5&&span>=30&&read&&write&&!latestWrong)status='習得';else if(dates.length>=3&&span>=7&&read&&write&&!latestWrong)status='もう少し';return{status,due,nextReview:latestWrong?localDate(new Date(now)):localDate(new Date(dueAt)),successfulDays:dates.length,spanDays:span}}
export function mastery(logs:AnswerLog[],kanji:string){return memoryProfile(logs,kanji).status}
export function merge(a:Store,b:Store):Store{const records=[...new Map([...a.records,...b.records].map(r=>[r.id,r])).values()];return {...a,records,settings:{...a.settings,...b.settings},importedIds:[...new Set([...a.importedIds,...b.importedIds])]}}
export const fnv=(s:string)=>{let h=2166136261;for(const c of s)h=(h^c.charCodeAt(0))*16777619>>>0;return h.toString(16)};
