import type {Store,StudyRecord,AnswerLog} from './types';
export const KEY='kanji-study-v1';
export const localDate=(d=new Date())=>{const y=d.getFullYear(),m=String(d.getMonth()+1).padStart(2,'0'),day=String(d.getDate()).padStart(2,'0');return `${y}-${m}-${day}`};
export const emptyStore=():Store=>({version:1,settings:{grade:'6級',examDate:'',dailyLimitMinutes:45,courseMode:'kanken',schoolGrade:'小学5年',schoolTerm:1},records:[],importedIds:[]});
export function migrate(raw:unknown):Store{try{
 const x=typeof raw==='string'?JSON.parse(raw):raw as any;if(!x||typeof x!=='object')return emptyStore();
 const base=emptyStore(),incoming=x.settings||{},settings={...base.settings,...incoming};
 if(!['10級','9級','8級','7級','6級','5級','4級','3級'].includes(settings.grade))settings.grade=base.settings.grade;
 if(!['kanken','school'].includes(settings.courseMode))settings.courseMode='kanken';
 if(!['小学1年','小学2年','小学3年','小学4年','小学5年','小学6年','中学1年','中学2年','中学3年'].includes(settings.schoolGrade))settings.schoolGrade=base.settings.schoolGrade;
 if(![1,2,3].includes(settings.schoolTerm))settings.schoolTerm=1;
 settings.dailyLimitMinutes=Number.isFinite(settings.dailyLimitMinutes)?Math.min(90,Math.max(10,settings.dailyLimitMinutes)):45;
 if(typeof settings.examDate!=='string'||!/^\d{4}-\d{2}-\d{2}$/.test(settings.examDate))settings.examDate='';
 const stringList=(a:any)=>Array.isArray(a)?a.filter((s:any)=>typeof s==='string'):[];
 const answerList=(a:any)=>Array.isArray(a)?a.filter((l:any)=>l&&typeof l.questionId==='string'&&typeof l.correct==='boolean'&&Array.isArray(l.kanji)&&l.kanji.every((k:any)=>typeof k==='string')&&Number.isFinite(Date.parse(l.at))&&typeof l.category==='string'&&['daily','mini','full'].includes(l.mode)).map((l:any)=>({...l,recall:l.recall??!/^k[46]-/.test(l.questionId)})):[];
 const records:StudyRecord[]=Array.isArray(x.records)?x.records.filter((r:any)=>r&&typeof r.id==='string'&&Number.isFinite(r.total)&&r.total>=0).map((r:any)=>({...r,version:1,date:typeof r.date==='string'?r.date:localDate(),completedAt:typeof r.completedAt==='string'?r.completedAt:new Date().toISOString(),grade:typeof r.grade==='string'?r.grade:'不明',activity:typeof r.activity==='string'?r.activity:'学習',correct:Number.isFinite(r.correct)?Math.max(0,Math.min(r.correct,r.total)):0,durationMinutes:Number.isFinite(r.durationMinutes)?r.durationMinutes:0,nextAction:typeof r.nextAction==='string'?r.nextAction:'漢字を復習',steps:Array.isArray(r.steps)?r.steps.map(Boolean):[true],answers:answerList(r.answers),learnedKanji:stringList(r.learnedKanji),masteredKanji:stringList(r.masteredKanji),wrongKanji:stringList(r.wrongKanji),strengths:stringList(r.strengths),weaknesses:stringList(r.weaknesses)})):[];
 let draft:Store['draft'];
 if(x.draft&&Number.isInteger(x.draft.index)&&x.draft.index>=0&&Number.isFinite(Date.parse(x.draft.startedAt))){draft={index:x.draft.index,answers:answerList(x.draft.answers),startedAt:x.draft.startedAt,questionIds:stringList(x.draft.questionIds),courseKey:typeof x.draft.courseKey==='string'?x.draft.courseKey:undefined,mode:x.draft.mode==='mini'?'mini':'daily',input:typeof x.draft.input==='string'?x.draft.input:'',feedback:typeof x.draft.feedback==='string'?x.draft.feedback:''};if(draft.questionIds?.length&&draft.index>=draft.questionIds.length)draft=undefined}
 return {version:1,settings,records:[...new Map(records.map((r:StudyRecord)=>[r.id,r])).values()],draft,importedIds:stringList(x.importedIds)}
 }catch{return emptyStore()}}

export function load():Store{try{return migrate(localStorage.getItem(KEY)||sessionStorage.getItem(KEY))}catch{try{return migrate(sessionStorage.getItem(KEY))}catch{return emptyStore()}}}
export function save(s:Store){try{localStorage.setItem(KEY,JSON.stringify(s));return 'local'}catch{try{sessionStorage.setItem(KEY,JSON.stringify(s));return 'session'}catch{return 'failed'}}}
const DAY=864e5,INTERVALS=[1,3,7,14,30];
export function memoryProfile(logs:AnswerLog[],kanji:string,now=Date.now()){const a=logs.filter(x=>Array.isArray(x.kanji)&&x.kanji.includes(kanji)&&Number.isFinite(Date.parse(x.at))).sort((x,y)=>new Date(x.at).getTime()-new Date(y.at).getTime());if(!a.length)return{status:'未学習',due:true,nextReview:null,successfulDays:0,spanDays:0};const lastWrong=a.findLastIndex(x=>!x.correct),correct=a.slice(lastWrong+1).filter(x=>x.correct&&x.recall!==false),dates=[...new Set(correct.map(x=>localDate(new Date(x.at))))],first=correct[0]&&new Date(correct[0].at).getTime(),last=correct.at(-1)&&new Date(correct.at(-1)!.at).getTime(),span=first&&last?Math.floor((last-first)/DAY):0,latest=a.at(-1)!,latestWrong=!latest.correct,read=correct.some(x=>x.category==='読み'),write=correct.some(x=>x.category==='書き'),level=Math.min(dates.length,INTERVALS.length),gap=INTERVALS[Math.max(0,level-1)],dueAt=latestWrong?now:(last||new Date(latest.at).getTime())+gap*DAY,due=now>=dueAt;let status='練習中';if(dates.length>=5&&span>=30&&read&&write&&!latestWrong)status='習得';else if(dates.length>=3&&span>=7&&read&&write&&!latestWrong)status='もう少し';return{status,due,nextReview:latestWrong?localDate(new Date(now)):localDate(new Date(dueAt)),successfulDays:dates.length,spanDays:span}}
export function mastery(logs:AnswerLog[],kanji:string){return memoryProfile(logs,kanji).status}
export function merge(a:Store,b:Store):Store{const records=[...new Map([...a.records,...b.records].map(r=>[r.id,r])).values()];return {...a,records,settings:{...b.settings,...a.settings},importedIds:[...new Set([...a.importedIds,...b.importedIds])]}}
export const fnv=(s:string)=>{let h=2166136261;for(const c of s)h=(h^c.charCodeAt(0))*16777619>>>0;return h.toString(16)};
