import type {Store,StudyRecord,AnswerLog} from './types';
export const KEY='kanji-study-v1';
export const localDate=(d=new Date())=>{const y=d.getFullYear(),m=String(d.getMonth()+1).padStart(2,'0'),day=String(d.getDate()).padStart(2,'0');return `${y}-${m}-${day}`};
export const emptyStore=():Store=>({version:1,settings:{grade:'6級',examDate:'',dailyLimitMinutes:45},records:[],importedIds:[]});
export function migrate(raw:unknown):Store{try{const x=typeof raw==='string'?JSON.parse(raw):raw as any;if(!x||typeof x!=='object')return emptyStore();const base=emptyStore();const records=Array.isArray(x.records)?x.records.filter((r:any)=>r&&r.id&&Number.isFinite(r.total)).map((r:any)=>({...r,version:1,steps:r.steps??[true,true,true,true,true],answers:r.answers??[]})):[];return {...base,...x,version:1,settings:{...base.settings,...x.settings},records:[...new Map(records.map((r:StudyRecord)=>[r.id,r])).values()]}}catch{return emptyStore()}}
export function load():Store{return migrate(localStorage.getItem(KEY)||sessionStorage.getItem(KEY))}
export function save(s:Store){try{localStorage.setItem(KEY,JSON.stringify(s));return 'local'}catch{try{sessionStorage.setItem(KEY,JSON.stringify(s));return 'session'}catch{return 'failed'}}}
export function mastery(logs:AnswerLog[],kanji:string){const a=logs.filter(x=>x.kanji.includes(kanji));const days=new Set(a.filter(x=>x.correct).map(x=>x.at.slice(0,10))).size;const read=a.some(x=>x.correct&&x.category==='読み'),write=a.some(x=>x.correct&&x.category==='書き');const latestWrite=[...a].reverse().find(x=>x.category==='書き');const recentWrong=a.some(x=>!x.correct&&Date.now()-new Date(x.at).getTime()<14*864e5);if(days>=3&&read&&write&&latestWrite?.correct&&!recentWrong)return '習得';if(a.filter(x=>x.correct).length>=2)return 'もう少し';if(a.length)return '練習中';return '未学習'}
export function merge(a:Store,b:Store):Store{const records=[...new Map([...a.records,...b.records].map(r=>[r.id,r])).values()];return {...a,records,settings:{...a.settings,...b.settings},importedIds:[...new Set([...a.importedIds,...b.importedIds])]}}
export const fnv=(s:string)=>{let h=2166136261;for(const c of s)h=(h^c.charCodeAt(0))*16777619>>>0;return h.toString(16)};
